### ISSUE TITLE
[Playground] Refactoring `OpenAIApiClient`

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#163]
- OpenAIApiClient.cs

    https://github.com/aliencube/azure-openai-sdk-proxy/blob/b1fcef0ee3b93a83a2b96e823fe3f8cfbe9a91ae/src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs#L27-L32

- OpenAIApiClientOptions.cs

    https://github.com/aliencube/azure-openai-sdk-proxy/blob/b1fcef0ee3b93a83a2b96e823fe3f8cfbe9a91ae/src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClientOptions.cs#L6-L41

- ChatWindowComponent.razor

    https://github.com/aliencube/azure-openai-sdk-proxy/blob/b1fcef0ee3b93a83a2b96e823fe3f8cfbe9a91ae/src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ChatWindowComponent.razor#L27-L55

They need to be refactored so that

- `AzureOpenAIClient` should be injected from `Program.cs`.
- `ApiKey` and `Endpoint` properties of `OpenAIApiClientOptions` should be removed.

**Comment by 5jisoo** [comment]
제가 작업중입니다~
