### ISSUE TITLE
[OpenAPI] Add endpoint for update event details

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#202]
- OpenAPI doc only - no implementation
- `PUT`
- `/admin/events/{eventID}`

**Comment by justinyoo** [comment]
- #203 
- #204 
- #205

**Comment by justinyoo** [comment]
@SeungHuLee 이 이슈 작업한다고 코멘트 먼저 남기고 시작해 주세요

**Comment by SeungHuLee** [comment]
> @SeungHuLee 이 이슈 작업한다고 코멘트 먼저 남기고 시작해 주세요

넵넵! 해당 이슈 제가 다음 PR에서 작업중입니다. https://github.com/aliencube/azure-openai-sdk-proxy/pull/241
