### ISSUE TITLE
[OpenAPI] Add endpoint for view event details

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#207]
- OpenAPI doc only - no implementation
- `GET`
- `/admin/events/{eventID}`

**Comment by justinyoo** [comment]
@juhangil 응답 개체 모델링을 좀 해야 할 듯 싶은데...  * 마크 있는 항목은 필수 항목

- ID: EventId *
- 제목: Title *
- 요약 (마크다운): Summary *
- 상세 (마크다운): Description
- 시작: DateStart *
- 종료: DateEnd *
- 타임존: TimeZone *
- 활성 여부: IsActive *
- 이벤트 소유자: OrganizerName *
- 이벤트 소유자 Email: OrganizerEmail *
- 이벤트 부소유자: CoorganizerNames
- 이벤트 부소유자 Email: CoorganizerEmails
- 1회 최대 토큰 크기: MaxTokenCap *
- 1일 최대 요청 횟수: DailyRequestCap *

뭐가 더 필요한가요? 각 항목별로 어떤 내용인지 알 수 있겠어요?

**Comment by juhangil** [comment]
Endpoint constant 파일을 AdminEventUrls.cs로 한다면 Endpoint 파일은 AdminEventEndpoints.cs로 하는게 통일성이 있어 보기 편할 것 같습니다

**Comment by justinyoo** [comment]
@juhangil 좋습니다! 그리고 제가 오타가 있었는데 `AdminEndpointUrls.cs` 로 하시는 게 맞을 것 같네욥. 어드민 관련 엔드포인트 죄다 모아둘 거니까.

**Comment by juhangil** [comment]
@justinyoo 넵 변경하겠습니다

> @juhangil 응답 개체 모델링을 좀 해야 할 듯 싶은데... * 마크 있는 항목은 필수 항목
> 
> * ID: EventId *
> * 제목: Title *
> * 요약 (마크다운): Summary *
> * 상세 (마크다운): Description
> * 시작: DateStart *
> * 종료: DateEnd *
> * 타임존: TimeZone *
> * 활성 여부: IsActive *
> * 이벤트 소유자: OrganizerName *
> * 이벤트 소유자 Email: OrganizerEmail *
> * 이벤트 부소유자: CoorganizerNames
> * 이벤트 부소유자 Email: CoorganizerEmails
> * 1회 최대 토큰 크기: MaxTokenCap *
> * 1일 최대 요청 횟수: DailyRequestCap *
> 
> 뭐가 더 필요한가요? 각 항목별로 어떤 내용인지 알 수 있겠어요?

OpenAI deployment list 가 추가로 필요할 것 같은데 조금 더 고민해보고 추가하겠습니다
늦은 시간에 감사드립니다

**Comment by justinyoo** [comment]
> OpenAI deployment list 가 추가로 필요할 것 같은데 조금 더 고민해보고 추가하겠습니다

@juhangil 이게 Azure OpenAI 모델 말하는 거죠? 요건 이벤트 보다는 이 모델 추가하는 것만 따로 엔드포인트를 잡는 게 나을 것 같아요. 같은 모델을 여러 이벤트에서도 사용할 수 있으니까.

**Comment by juhangil** [comment]
@justinyoo 멘토님 테스트 코드 작성 중에 매 테스트마다 aspire host를 생성해서 테스트 시간이 길어지는 것 같습니다.

`public class AspireHostFixture : IAsyncLifetime
{
    public DistributedApplication? App { get; private set; }

    public async Task InitializeAsync()
    {
        var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.AzureOpenAIProxy_AppHost>();
        this.App = await appHost.BuildAsync();
        await App.StartAsync();

        Assert.NotNull(App);
    }

    public async Task DisposeAsync()
    {
        if (App == null) return;

        await App.StopAsync();
        await App.DisposeAsync();
    }
}`

Aspire host 생성은 Fixture로 따로 빼서 주입하는 형식으로 만들어봤는데 어떨까요?

**Comment by justinyoo** [comment]
@juhangil 오 좋습니다! 한 번 해 보시지욥

**Comment by juhangil** [comment]
@justinyoo 멘토님 테스트 작성 중에 아리송한게 있습니다. swagger json에 component schema를 테스트한다고 하면 이렇게 하는게 맞는지 아니면 단순하게 존재 여부만 확인하고 넘어가는게 맞을까요?

```csharp
[Theory]
[InlineData("eventId", true, "string")]
[InlineData("title", true, "string")]
[InlineData("summary", true, "string")]
[InlineData("description", false, "string")]
[InlineData("dateStart", true, "string")]
[InlineData("dateEnd", true, "string")]
[InlineData("timeZone", true, "string")]
[InlineData("isActive", true, "boolean")]
[InlineData("organizerName", true, "string")]
[InlineData("organizerEmail", true, "string")]
[InlineData("coorganizerName", false, "string")]
[InlineData("coorganizerEmail", false, "string")]
[InlineData("maxTokenCap", true, "integer")]
[InlineData("dailyRequestCap", true, "integer")]
public async Task Given_Resource_When_Invoked_Endpoint_Then_It_Should_Return_Component_Property
    (string propName, bool isRequired, string type)
{
    // Arrange
    using var httpClient = host.App!.CreateHttpClient("apiapp");

    // Act
    var json = await httpClient.GetStringAsync("/swagger/v1.0.0/swagger.json");
    var openapi = JsonSerializer.Deserialize<JsonDocument>(json);

    // Assert
    var component = openapi!.RootElement.GetProperty("components")
                                        .GetProperty("schemas")
                                        .GetProperty("AdminEventDetails");

    component.ValueKind.Should().Be(JsonValueKind.Object);

    var required = component.TryGetStringArray("required").ToList();
    required.Contains(propName).Should().Be(isRequired);

    var result = component.GetProperty("properties")
                        .TryGetProperty(propName, out var propDetail) ? propDetail : default;

    result.ValueKind.Should().Be(JsonValueKind.Object);
    result.TryGetString("type").Should().Be(type);
}
```

**Comment by justinyoo** [comment]
음... 이 테스트는 너무 많은 걸 한번에 몰아서 테스트하기 때문에, 저라면 테스트 메소드 네 개로 쪼갤 것 같습니다.

1. `AdminEventDetails`가 존재하면서 그게 `Object`인가
2. 특정 `propName`이 존재하면서 그게 `Object`인가
3. 특정 `propName`이 `required`인가
4. 특정 `propName`의 type이 무엇인가

이유는 말 그대로 단위테스트라서, 메소드 하나당 하나만 집중해서 테스트하는 것이 좋기 때문입니다.

**Comment by justinyoo** [comment]
그리고 다른 곳에서는 `propName` 대신 `attribute`를 썼던 것 같은데, 한가지로 통일하면 좋을 것 같아요. 어느쪽이든 상관 없습니다.
