### ISSUE TITLE
[Backend API] Implement endpoint for view event details

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#208]
- Based on #207 
- Implement the endpoint

**ASSUMPTION**: You've logged in as admin

**Comment by sikutisa** [comment]
이 이슈 해결해보겠습니다.

**Comment by justinyoo** [comment]
@sikutisa 이 이슈 작업하시면서 아마도 서비스 레이어와 리포지토리 레이어를 만들게 될 것 같은데, 그쪽 설계부터 먼저 시작하는 태스크부터 잡고 갈까요?

**Comment by sikutisa** [comment]
> @sikutisa 이 이슈 작업하시면서 아마도 서비스 레이어와 리포지토리 레이어를 만들게 될 것 같은데, 그쪽 설계부터 먼저 시작하는 태스크부터 잡고 갈까요?

네. 그렇게 하는 게 좋을 것 같습니다.
