### ISSUE TITLE
[OpenAPI] Add endpoint for list event details

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#217]
- OpenAPI doc only - no implementation
- `GET`
- `/admin/events`

**Comment by praivesi** [comment]
찜!

**Comment by praivesi** [comment]
찜!

**Comment by tae0y** [comment]
진행해보겠습니다 !

**Comment by tae0y** [comment]
이런 것을 고민해보고 있어욥

- 엔드포인트 이름 : `/admin/eventlist`
- Request 파라미터는
  - 별도 지정없이 해당되는 모든 이벤트 목록을 조회
- Response 반환타입은
  - `AdminEventDetails` 모델을 `List<>`로 감싸 재사용
  - 불필요한 파라미터는 차후에 lazy loading? 혹은 null로? AdminEventSummary와 같은 별도 모델로 분리?
