### ISSUE TITLE
[GitHub Actions] Add OpenAPI linting

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#221]
- Based on #20 
- Everytime app codes are pushed, it should run the OpenAPI linting

**Comment by justinyoo** [comment]
- https://docs.stoplight.io/docs/spectral/9ffa04e052cc1-spectral-cli
- https://github.com/marketplace/actions/spectral-linting
- https://github.com/marketplace/actions/lint-openapi-and-asyncapi-spectral
- warning 또는 error 발생했을 경우 fail로 처리

**Comment by justinyoo** [comment]
@sikutisa 여기에 코멘트 먼저 남겨서 작업 시작한다고 하고 시작해 주세요. 그래야 제가 이 이슈를 할당할수 있습니다

**Comment by sikutisa** [comment]
현재 제가 작업하고 있습니다.
