### ISSUE TITLE
[Playground] Component - Tab for system message and parameters (UI only)

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#225]
- Implement a tab that contains both System Message and Parameters
- It should indicate which tab is clicked

**Comment by justinyoo** [comment]
@5jisoo 여기에 지수님이 작업한다고 코멘트 남겨 주세요!

**Comment by 5jisoo** [comment]
제가 작업하고 있습니다 🧐 ~!!
