### ISSUE TITLE
[Admin] 스토리지 커넥션 개체 생성

### ISSUE THREAD

**Issue by justinyoo** [aliencube/azure-openai-sdk-proxy#300]
- #283 의 bicep을 통해 만든 스토리지 어카운트 커넥션 개체를 생성
- `TableServiceClient` 인스턴스 IoC 컨테이너 추가

**Comment by sikutisa** [comment]
> * [[DevOps] Table Storage용 bicep 파일 만들기 #283](https://github.com/aliencube/azure-openai-sdk-proxy/issues/283) 의 bicep을 통해 만든 스토리지 어카운트 커넥션 개체를 생성
> * `TableServiceClient` 인스턴스 IoC 컨테이너 추가

현재 제가 #299 PR에서 작업하고 있습니다.
